#!/usr/bin/env python3
"""Bidirectional traceability between docs/assurance/requirements.md and the tests.

A test carries a tag comment `Verifies: ID[, ID...]` on its registry line or within the three lines
above it (`//` in C#, `--` in Lua, `#` in shell and config). `Verifies: none (reason)` marks a test
that traces to no requirement and says why; these are listed, not hidden.

Checks (exit 1 on any):
  1. every requirement is verified by at least one tagged test or other evidence file;
  2. every tag names an existing requirement;
  3. every test is tagged;
  4. with --check: docs/assurance/traceability.md is what this script generates now.

Tests are enumerated from the registries of the suites:
  protocol   backend/tests/Dbbliss.ProtocolTests/Program.cs   ("name", "bug", Fn)
  cancel     backend/tests/Dbbliss.CancelTests/Scenarios.cs   yield return ("name", ...)
  lua:*      tests/nvim/*_test.lua                            a line holding only 'name',
Other evidence (not subject to check 3): spec/check.sh, .editorconfig.

Only the standard library is used.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
REQS = ROOT / "docs/assurance/requirements.md"
OUT = ROOT / "docs/assurance/traceability.md"

SUITES = [
    ("protocol", "backend/tests/Dbbliss.ProtocolTests/Program.cs", r'^\s*\("([a-z0-9_]+)",\s*"'),
    ("cancel", "backend/tests/Dbbliss.CancelTests/Scenarios.cs", r'yield return \("([a-z0-9_]+)"'),
    ("lua-client", "tests/nvim/client_test.lua", r"^\s*'([a-z0-9_]+)',\s*$"),
    ("lua-results", "tests/nvim/results_test.lua", r"^\s*'([a-z0-9_]+)',\s*$"),
    ("lua-catalog", "tests/nvim/catalog_test.lua", r"^\s*'([a-z0-9_]+)',\s*$"),
    ("lua-sessions", "tests/nvim/sessions_test.lua", r"^\s*'([a-z0-9_]+)',\s*$"),
    ("e2e", "tests/nvim/e2e_test.lua", r"^\s*'([a-z0-9_]+)',\s*$"),
]
OTHER = ["spec/check.sh", ".editorconfig"]
TAG = re.compile(r"(?://|--|#)\s*Verifies:\s*(.+?)\s*$")
ID = re.compile(r"\b((?:HLR|LLR)-[A-Z0-9]+-\d+)\b")


def requirements():
    reqs = {}
    cur = None
    for line in REQS.read_text().splitlines():
        m = re.match(r"^### ((?:HLR|LLR)-[A-Z0-9]+-\d+)\s*$", line)
        if m:
            cur = m.group(1)
            if cur in reqs:
                sys.exit(f"duplicate requirement {cur}")
            reqs[cur] = ""
        elif line.startswith("#"):
            cur = None
        elif cur and line.strip():
            reqs[cur] += (" " if reqs[cur] else "") + line.strip()
    return reqs


def tags_near(lines, i):
    """Tags on line i or the three lines above it. -> (ids, none_reason or None)"""
    ids, none = [], None
    for j in range(max(0, i - 3), i + 1):
        m = TAG.search(lines[j])
        if not m:
            continue
        body = m.group(1)
        if body.lower().startswith("none"):
            none = body
        else:
            ids += ID.findall(body)
    return ids, none


def collect():
    tests = []  # (suite, name, file, line, ids, none)
    for suite, rel, pattern in SUITES:
        lines = (ROOT / rel).read_text().splitlines()
        rx = re.compile(pattern)
        for i, line in enumerate(lines):
            m = rx.search(line)
            if m:
                ids, none = tags_near(lines, i)
                tests.append((suite, m.group(1), rel, i + 1, ids, none))
    others = []
    for rel in OTHER:
        p = ROOT / rel
        if not p.exists():
            continue
        for i, line in enumerate(p.read_text().splitlines()):
            m = TAG.search(line)
            if m:
                others.append((rel, i + 1, ID.findall(m.group(1))))
    return tests, others


def main():
    reqs = requirements()
    tests, others = collect()
    problems = []

    by_req = {r: [] for r in reqs}
    for suite, name, rel, line, ids, none in tests:
        for rid in ids:
            if rid not in reqs:
                problems.append(f"{rel}:{line} {suite}:{name} verifies unknown requirement {rid}")
            else:
                by_req[rid].append(f"{suite}:{name}")
        if not ids and not none:
            problems.append(f"{rel}:{line} {suite}:{name} has no `Verifies:` tag")
    other_by_req = {r: [] for r in reqs}
    for rel, line, ids in others:
        for rid in ids:
            if rid not in reqs:
                problems.append(f"{rel}:{line} verifies unknown requirement {rid}")
            else:
                other_by_req[rid].append(f"{rel}:{line}")
    for rid in reqs:
        if not by_req[rid] and not other_by_req[rid]:
            problems.append(f"{rid} is not verified by any test or evidence file")

    md = ["# Traceability matrix", "",
          "Generated by `scripts/assurance/trace.py`; do not edit. Requirements: `requirements.md`.", "",
          f"{len(reqs)} requirements, {len(tests)} tests ({sum(1 for t in tests if t[4])} traced, "
          f"{sum(1 for t in tests if not t[4] and t[5])} marked `none`).", "",
          "## Requirement → verification", "", "| Requirement | Verified by |", "|---|---|"]
    for rid in sorted(reqs):
        ev = sorted(set(by_req[rid])) + [f"`{o}`" for o in sorted(set(other_by_req[rid]))]
        md.append(f"| {rid} | {', '.join(ev) if ev else '**NONE**'} |")
    md += ["", "## Test → requirements", "", "| Test | Requirements |", "|---|---|"]
    for suite, name, rel, line, ids, none in sorted(tests):
        md.append(f"| {suite}:{name} | {', '.join(sorted(set(ids))) if ids else (none or '**UNTAGGED**')} |")
    text = "\n".join(md) + "\n"

    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            problems.append("docs/assurance/traceability.md is out of date: run scripts/assurance/trace.py")
    else:
        OUT.write_text(text)
    for p in problems:
        print("ERROR:", p, file=sys.stderr)
    print(f"{len(reqs)} requirements, {len(tests)} tests, {len(problems)} problem(s)")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
